#!/bin/bash

DIR=`dirname $?`
DIR=`readlink -f $DIR`

source $DIR/config

ACCESS_TOKEN=`curl --insecure -s --data "client_id=admin-cli&username=admin&password=admin&grant_type=password" $KEYCLOAK_URL/realms/master/protocol/openid-connect/token | jq -r '.access_token'`

echo $ACCESS_TOKEN
